language: ruby
rvm:
- 2.2.0

env:
  global:
  - PAGES_REPO_URI=git@github.com:love2d-community/splashes.git
  - DEST_FILE=game.js

before_install:
- openssl aes-256-cbc -K $encrypted_155b7c1239eb_key -iv $encrypted_155b7c1239eb_iv
  -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d

script:
- ruby .travis/package_game.rb . main.lua */*.png */*.lua > game.js

after_success:
- .travis/pages.sh
